### ISSUE TITLE
Thoughtful documentation

### ISSUE THREAD

**Issue by robinpokorny** [lmc-eu/emerald#3]
The documentation should be easy to understand for beginners as well as to provide enough background information and examples for an advanced use and configuration.

**Comment by OndraM** [comment]
:+1:

**Comment by s7anley** [comment]
Please emphasize that the use of visible and hidden classes define properties for a specific type of device. It may be, that users will attempt to define it the same way as in the grid.

```
<a class="visible--palm hidden--lap hidden--desk">Only mobile link </a>
```

**Comment by robinpokorny** [comment]
@s7anley Agreed. It is intended that responsive visibility classes should copy the behaviour of the grid in the next version. There is discussion about inline-block visibility, thought.

**Comment by robinpokorny** [comment]
The documentation is now maintained in the Wiki. The Quick Start seems understandable by beginners and there are some TODO's for future development.
