### ISSUE TITLE
.hidden-- classes does not work with .grid__item

### ISSUE THREAD

**Issue by jirinovak** [lmc-eu/emerald#4]
In some situation it would be useful to hide whole grid item (element with `.grid__item` class). Now it is not possible, because `.hidden--` classes set `display: block;` which doesn't work well with grid system.

Or did i miss something and there is another way how to hide whole grid item?

**Comment by robinpokorny** [comment]
Responsive classes `.hidden` and `.visible` are not intended to be used on grid items but rather on blocks inside them to switch the content.

However I see the value of the ability to hide the whole grid item so in v0.3.1 (33bf66d) I added `e-0` notion for hiding the grid item. This is (IMO) a consistent way of describing such behaviour.

Example: `.grid__item.e-0--palm.e-4.e-0--desk` would be hidden on palm, size 4 on palm and hidden again on desk.

**Comment by robinpokorny** [comment]
Needs to be refactored!

`.grid__item.e-0` will be visible on desk!

**Comment by rokerkony** [comment]
i have similar issue... 

```
div.grid__item.e-0--palm.e-0.e-7--desk
```

this div is not visible on desktop but should

fix can be something like this:

```
    @media only screen and (min-width: 1020px) {
        .grid__item {
            display: inline-block;
        }
        .e-0--desk {
            display: none;
        }
    }
```
