### ISSUE TITLE
Comic Sans on product page

### ISSUE THREAD

**Issue by OndraM** [lmc-eu/emerald#9]
My eyes! My eyes!

On my Firefox & Chrome (both latest versions) on Linux, I'm having Emerald homepage headers written in _Comic Sans_.

And according to this: http://browsershots.org/https://lmc-eu.github.io/emerald/, some windows browsers (the screenshots are from Chrome 33 & Firefox 29 on Windows 2008) could suffer as well.

Specifying the `font-family: 'Poiret One',cursive` is obviously having a bit unexpected results there :-o.

**Comment by robinpokorny** [comment]
New page should not have this issue.

If anyone will encounter the same problem, please reopen / comment this ticket.
